# Generated by Django 5.2.4 on 2025-07-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('adi', models.CharField()),
                ('soyadi', models.CharField()),
                ('dogum_tarihi', models.DateField()),
                ('okul', models.CharField()),
                ('telefon', models.CharField(blank=True, null=True)),
                ('veli', models.CharField()),
                ('veli_telefon', models.CharField()),
                ('veli_eposta', models.EmailField(max_length=254)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.takim')),
            ],
        ),
    ]
