# Generated by Django 5.2.4 on 2025-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
