# Generated by Django 5.2.4 on 2025-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0002_alter_sporcu_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='renk',
            field=models.CharField(default='red'),
        ),
    ]
