# Generated by Django 5.2.4 on 2025-07-17 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0004_sporcu_aktif_sporcu_created_takim_aktif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporcu',
            name='id',
        ),
        migrations.AddField(
            model_name='sporcu',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
