# Generated by Django 5.2.4 on 2025-07-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0005_remove_sporcu_id_sporcu_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sporcu',
            old_name='uuid',
            new_name='id',
        ),
    ]
