# Generated by Django 5.2.4 on 2025-07-17 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0006_rename_uuid_sporcu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
