# Generated by Django 5.2.4 on 2025-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0007_sporcu_uuid_alter_sporcu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporcu',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='sporcu',
            name='created',
        ),
        migrations.RemoveField(
            model_name='takim',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='takim',
            name='created',
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
