# Generated by Django 5.2.4 on 2025-07-18 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0008_remove_sporcu_aktif_remove_sporcu_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sporcu',
            old_name='uuid',
            new_name='s_uuid',
        ),
        migrations.AddField(
            model_name='sporcu',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takim',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='takim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
