# Generated by Django 5.2.4 on 2025-07-18 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0009_rename_uuid_sporcu_s_uuid_sporcu_aktif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='s_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
