# Generated by Django 5.2.4 on 2025-07-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0010_alter_sporcu_s_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporcu',
            name='dogum_tarihi',
        ),
    ]
