# Generated by Django 5.2.4 on 2025-07-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0011_remove_sporcu_dogum_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporcu',
            name='s_uuid',
        ),
    ]
