# Generated by Django 5.2.4 on 2025-07-18 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0012_remove_sporcu_s_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='dogum_tarihi',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
