# Generated by Django 5.2.4 on 2025-07-18 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0013_sporcu_dogum_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='s_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
