# Generated by Django 5.2.4 on 2025-07-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0014_sporcu_s_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='takim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='takim.takim'),
        ),
    ]
