# Generated by Django 5.2.4 on 2025-07-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0015_alter_sporcu_takim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saglik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kronik_hastalik', models.CharField()),
                ('sakatlik_ameliyat', models.CharField()),
                ('kullanilan_ilac', models.CharField()),
                ('alerji', models.CharField()),
                ('kalp', models.CharField()),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.sporcu')),
            ],
        ),
        migrations.CreateModel(
            name='YuzmeBilgilieri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuzme_gecmisi', models.CharField()),
                ('yuzme_bilgisi', models.CharField()),
                ('derinlik', models.CharField()),
                ('su_korkusu', models.CharField()),
                ('denizde_yuzme', models.CharField()),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.sporcu')),
            ],
        ),
    ]
