# Generated by Django 5.2.4 on 2025-07-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0016_saglik_yuzmebilgilieri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saglik',
            name='alerji',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saglik',
            name='kalp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saglik',
            name='kronik_hastalik',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saglik',
            name='kullanilan_ilac',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saglik',
            name='sakatlik_ameliyat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='YuzmeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuzme_gecmisi', models.CharField(blank=True, null=True)),
                ('yuzme_bilgisi', models.CharField(blank=True, null=True)),
                ('derinlik', models.CharField(blank=True, null=True)),
                ('su_korkusu', models.CharField(blank=True, null=True)),
                ('denizde_yuzme', models.CharField(blank=True, null=True)),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.sporcu')),
            ],
        ),
        migrations.DeleteModel(
            name='YuzmeBilgilieri',
        ),
    ]
