# Generated by Django 5.2.4 on 2025-07-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0017_alter_saglik_alerji_alter_saglik_kalp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='alerji',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='kalp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='kronik_hastalik',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='kullanilan_ilac',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='sakatlik_ameliyat',
            field=models.CharField(blank=True, null=True),
        ),
    ]
