# Generated by Django 5.2.4 on 2025-07-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0018_sporcu_alerji_sporcu_kalp_sporcu_kronik_hastalik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yuzmebilgileri',
            name='sporcu',
        ),
        migrations.AddField(
            model_name='sporcu',
            name='denizde_yuzme',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='derinlik',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='su_korkusu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='yuzme_bilgisi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='yuzme_gecmisi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Saglik',
        ),
        migrations.DeleteModel(
            name='YuzmeBilgileri',
        ),
    ]
