# Generated by Django 5.2.4 on 2025-07-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0019_remove_yuzmebilgileri_sporcu_sporcu_denizde_yuzme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='kronik_hastalik',
            field=models.CharField(blank=True, default='Yok', null=True),
        ),
    ]
