# Generated by Django 5.2.4 on 2025-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0020_alter_sporcu_kronik_hastalik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='kronik_hastalik',
            field=models.CharField(blank=True, default='Bilgi verilmedi', null=True),
        ),
    ]
