# Generated by Django 5.2.4 on 2025-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0022_alter_sporcu_alerji_alter_sporcu_denizde_yuzme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='alerji',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='denizde_yuzme',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='derinlik',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kalp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kronik_hastalik',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kullanilan_ilac',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='sakatlik_ameliyat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='su_korkusu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='yuzme_bilgisi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='yuzme_gecmisi',
            field=models.CharField(blank=True, null=True),
        ),
    ]
