# Generated by Django 5.2.4 on 2025-07-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0023_alter_sporcu_alerji_alter_sporcu_denizde_yuzme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='istek_yuzme',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='neden_yuzme',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='vade_yuzme',
            field=models.CharField(blank=True, null=True),
        ),
    ]
