# Generated by Django 5.2.4 on 2025-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0024_sporcu_istek_yuzme_sporcu_neden_yuzme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='dikkat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='iliski',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='kalabalik',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='komut',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='sosyal',
            field=models.CharField(blank=True, null=True),
        ),
    ]
