# Generated by Django 5.2.4 on 2025-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0025_sporcu_dikkat_sporcu_iliski_sporcu_kalabalik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='aile_not',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='antrenor_not',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='diger_spor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='katilim',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='ulasim',
            field=models.CharField(blank=True, null=True),
        ),
    ]
