# Generated by Django 5.2.4 on 2025-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0026_sporcu_aile_not_sporcu_antrenor_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='denizde_yuzme',
            field=models.TextField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Evet'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='derinlik',
            field=models.TextField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='su_korkusu',
            field=models.TextField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır'),
        ),
    ]
